import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import crypto from 'node:crypto';import http from 'node:http';import {spawnSync} from 'node:child_process';
import {readVerifiedBytes} from '../src/verified-file.mjs';import {readPublicEvidence,listPublicEvidence,assertPublicEvidence} from '../src/public-evidence.mjs';
const digest=b=>crypto.createHash('sha256').update(b).digest('hex');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'vidra-bytes-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const file=path.join(root,'content.mp4'),bytes=Buffer.from('accepted exact byte version');fs.writeFileSync(file,bytes);return{root,file,bytes};}
test('HTTP delivery uses verified snapshot even when pathname is replaced before sending',async t=>{
 const {root,file,bytes}=fixture(t),server=http.createServer((_req,res)=>{const snapshot=readVerifiedBytes(file,digest(bytes),{root});fs.unlinkSync(file);fs.writeFileSync(file,'unapproved replacement');res.end(snapshot.bytes);});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const response=await fetch(`http://127.0.0.1:${server.address().port}/`);assert.deepEqual(Buffer.from(await response.arrayBuffer()),bytes);assert.notDeepEqual(fs.readFileSync(file),bytes);
});
test('in-place writes after verification cannot alter returned byte snapshot',t=>{const {root,file,bytes}=fixture(t);const snapshot=readVerifiedBytes(file,digest(bytes),{root});fs.writeFileSync(file,'different bytes');assert.deepEqual(snapshot.bytes,bytes);assert.throws(()=>readVerifiedBytes(file,digest(bytes),{root}),/hash mismatch/);});
test('wrong hash, missing digest, malformed digest and bounded oversize fail closed',t=>{const {root,file,bytes}=fixture(t);for(const hash of [undefined,'A'.repeat(64),'bad'])assert.throws(()=>readVerifiedBytes(file,hash,{root}),/SHA-256/);assert.throws(()=>readVerifiedBytes(file,'0'.repeat(64),{root}),/hash mismatch/);assert.throws(()=>readVerifiedBytes(file,digest(bytes),{root,maxBytes:bytes.length-1}),/byte limit/);assert.throws(()=>readVerifiedBytes(file,digest(bytes),{root,maxBytes:Infinity}),/byte limit/);});
test('matching-byte files outside root, sibling-prefix directories and symlink aliases are rejected',t=>{const {root,file,bytes}=fixture(t),sibling=root+'-sibling';fs.mkdirSync(sibling);t.after(()=>fs.rmSync(sibling,{recursive:true,force:true}));const outside=path.join(sibling,'same.mp4');fs.writeFileSync(outside,bytes);assert.throws(()=>readVerifiedBytes(outside,digest(bytes),{root}),/escaped/);const alias=path.join(root,'alias.mp4');fs.symlinkSync(file,alias);assert.throws(()=>readVerifiedBytes(alias,digest(bytes),{root}),/Symbolic/);});
test('directories and FIFO substitutions are rejected without blocking an open',t=>{const {root,bytes}=fixture(t);assert.throws(()=>readVerifiedBytes(root,digest(bytes),{root}),/Regular/);const fifo=path.join(root,'pipe');const mk=spawnSync('mkfifo',[fifo]);if(mk.status!==0){t.skip('mkfifo not available on this platform');return;}assert.throws(()=>readVerifiedBytes(fifo,digest(bytes),{root}),/Regular/);});
test('unlisted and restricted reports cannot become public evidence',t=>{const {root}=fixture(t);fs.writeFileSync(path.join(root,'UNLISTED_REVIEW.json'),JSON.stringify({syntheticCanary:true}));assert.throws(()=>readPublicEvidence(root,'UNLISTED_REVIEW.json'),/not approved/);const approved='BASE_DEPLOYMENT_MANIFEST.json';fs.writeFileSync(path.join(root,approved),JSON.stringify({chainId:84532,private_key:'synthetic forbidden field'}));assert.deepEqual(listPublicEvidence(root),[]);assert.throws(()=>readPublicEvidence(root,approved),/Restricted/);fs.writeFileSync(path.join(root,approved),JSON.stringify({chainId:84532,tokenId:'8'}));assert.deepEqual(listPublicEvidence(root),[approved]);assert.equal(readPublicEvidence(root,approved).tokenId,'8');});
test('public evidence scanning rejects nested secret aliases without rejecting public technical identifiers',()=>{for(const key of ['privateKey','seed_phrase','csrf','rawTransaction','signature'])assert.throws(()=>assertPublicEvidence({nested:[{[key]:'synthetic'}]}),/Restricted/);assert.doesNotThrow(()=>assertPublicEvidence({tokenId:'8',sha256:'a'.repeat(64),signatureVerified:true}));});
