import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {MESSAGES,t,setLanguage} from '../public/studio-i18n.mjs';
const html=fs.readFileSync(new URL('../public/studio.html',import.meta.url),'utf8');
test('studio translations cover static UI, defaults and all fifteen gate labels without changing technical values',()=>{
 for(const match of html.matchAll(/data-i18n(?:-aria|-value)?="([^"]+)"/g))for(const lang of ['ru','en'])assert.ok(MESSAGES[match[1]]?.[lang],match[1]);
 for(const [key,pair]of Object.entries(MESSAGES))assert.ok(!/[А-Яа-яЁё]/.test(pair.en),key);
 setLanguage('en');assert.equal(t('Зарегистрированный инициатор'),'Registered initiator');assert.equal(t('0x'+'ab'.repeat(20)),'0x'+'ab'.repeat(20));assert.equal(t('<img src=x onerror=bad>'),'<img src=x onerror=bad>');setLanguage('ru');
});
test('actual studio language switch preserves form values, selection, IDs and fail-closed operation gates without requests',async()=>{
 const keys=['document','location','history','localStorage','sessionStorage','fetch','setInterval','setTimeout'];const old=new Map(keys.map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));
 class Element{constructor(){this.dataset={};this.value='';this.textContent='';this.innerHTML='';this.disabled=false;this.events={};this.classList={contains:()=>false,toggle(){}};}setAttribute(k,v){this[k]=v;}addEventListener(k,fn){this.events[k]=fn;}}
 const ids=new Map([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],new Element()]));
 const languages=['ru','en'].map(lang=>{const e=new Element();e.dataset.language=lang;return e;});const filters=['all','video'].map(kind=>{const e=new Element();e.dataset.kind=kind;return e;});
 ids.get('listing-title').dataset.i18nValue='sv0';ids.get('listing-title').value=MESSAGES.sv0.ru;ids.get('listing-description').dataset.i18nValue='sv1';ids.get('listing-description').value=MESSAGES.sv1.ru;ids.get('listing-kind').value='video';
 const staticNodes=[new Element()];staticNodes[0].dataset.i18n='st007';
 const controls=[...ids.values(),...languages,...filters];const doc={documentElement:{lang:'ru'},body:{classList:{contains:()=>false,toggle(){}}},getElementById:id=>ids.get(id),querySelectorAll(selector){return selector==='[data-language]'?languages:selector==='[data-i18n]'?staticNodes:selector==='[data-i18n-value]'?[ids.get('listing-title'),ids.get('listing-description')]:selector==='button'?controls:selector==='#filters button'||selector==='[data-kind]'?filters:[];}};
 const address='0x'+'12'.repeat(20),tx='0x'+'ab'.repeat(32),hash='ab'.repeat(32),assetId='asset-video',offerId='136',exchangeId='253';
 const certificate={tokenId:'4',owner:address,tx};
 const asset={id:assetId,kind:'video',title:'Проверенный выпуск NFT · Safe 3/5',sha256:hash,certificate,quality:{width:1920,height:1080,codec:'h264',duration:8,bytes:8632429,sourceWidth:3840,sourceHeight:2160}};
 const snapshot={csrf:'mock-csrf',active:null,pendingTransaction:false,paused:false,deploymentReady:true,chainView:{verified:true,block:123},manifest:{chainId:84532,nft:address,safe:address,sourceBoson:address,credit:address},commerce:{buyerBalance:'9856.5',sellerAvailable:'0'},releases:[],marketplace:{paused:false,assets:[asset],listings:[{id:'listing-136',kind:'video',offerId,title:'<img src=x onerror=bad>',description:'Готовое тестовое предложение монтажной студии.',price:'25',quantityAvailable:7,available:true,assetId,certificate,assetSha256:hash,tx}],timeline:[{title:'Предложение опубликовано в Boson',at:'2026-10-03T17:00:00Z',exchangeId,tx}]},orders:[{exchangeId,offerId,title:'Монтажная услуга · demo',state:'COMPLETED',price:'25',assetId,deliveredSha256:hash,txs:[]}],auditVerified:true,receipts:[{label:'boson-complete',block:123,tx}],checks:[{id:'first',passed:true}],checkDefinitions:[{id:'first',number:1,label:'Registered initiator'}]};
 const storage=new Map([['aim-asset',assetId]]),requests=[];let poll,offline=false;
 const store={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)};
 globalThis.document=doc;globalThis.location={search:'',href:'http://127.0.0.1:18339/#studio'};globalThis.history={replaceState(_a,_b,url){globalThis.location.href=String(url);}};globalThis.localStorage=store;globalThis.sessionStorage=store;globalThis.setTimeout=()=>0;globalThis.setInterval=fn=>{poll=fn;return 1;};
 globalThis.fetch=async(url,options={})=>{requests.push([url,options.method||'GET']);if(url==='/api/state')return{ok:!offline,json:async()=>offline?{error:'RPC unavailable'}:structuredClone(snapshot)};if(url==='/api/market/master/'+assetId)return{ok:true,blob:async()=>new Blob(['video'])};throw new Error('Unexpected request '+url);};
 try{setLanguage('ru');await import('../public/studio.mjs?test='+Date.now());ids.get('listing-title').value='My creator title';ids.get('listing-title').events.input();ids.get('listing-description').value='My original terms';ids.get('listing-description').events.input();
  ids.get('filters').events.click({target:{closest:()=>filters[1]}});const before=requests.length;languages[1].events.click();
  assert.equal(requests.length,before,'language switch makes no reads or writes');assert.equal(ids.get('asset-select').value,assetId);assert.equal(ids.get('listing-title').value,'My creator title');assert.equal(ids.get('listing-description').value,'My original terms');assert.match(ids.get('catalog').innerHTML,/data-buy="listing-136"/);assert.match(ids.get('catalog').innerHTML,/Public offer #136/);assert.match(ids.get('catalog').innerHTML,/&lt;img src=x onerror=bad&gt;/);assert.ok(!ids.get('catalog').innerHTML.includes('<img src=x'));
  assert.match(ids.get('order-list').innerHTML,/#253/);assert.match(ids.get('order-list').innerHTML,/Completed/);assert.equal(snapshot.marketplace.listings[0].offerId,offerId);assert.equal(snapshot.orders[0].exchangeId,exchangeId);
  snapshot.active='mint';await poll();assert.equal(ids.get('tokenize').disabled,true);assert.equal(languages[0].disabled,false);let count=requests.length;languages[0].events.click();assert.equal(requests.length,count);assert.equal(ids.get('tokenize').disabled,true,'language cannot bypass an active operation');
  snapshot.active=null;offline=true;await poll();count=requests.length;languages[1].events.click();assert.equal(requests.length,count);assert.equal(ids.get('publish').disabled,true,'language cannot bypass unavailable chain verification');assert.match(ids.get('connection').textContent,/verification unavailable/);assert.ok(requests.every(([,method])=>method==='GET'));
 }finally{for(const [key,descriptor]of old)if(descriptor)Object.defineProperty(globalThis,key,descriptor);else delete globalThis[key];setLanguage('ru');}
});
